export const CHANNEL_ACTION_TYPES = {
    FETCH_CHANNEL_BY_ID_START: "FETCH_CHANNEL_BY_ID_START",
    FETCH_CHANNEL_BY_ID_SUCCESS: "FETCH_CHANNEL_BY_ID_SUCCESS",
    FETCH_CHANNEL_BY_ID_FAILED: "FETCH_CHANNEL_BY_ID_FAILED",

    FETCH_SUBSCRIPTION_STATUS_START: "FETCH_SUBSCRIPTION_STATUS_START",
    FETCH_SUBSCRIPTION_STATUS_SUCCESS: "FETCH_SUBSCRIPTION_STATUS_SUCCESS",
    FETCH_SUBSCRIPTION_STATUS_FAILED: "FETCH_SUBSCRIPTION_STATUS_FAILED"
}