export const VIDEOS_ACTION_TYPES = {
    FETCH_POPULAR_VIDEOS_START: "FETCH_POPULAR_VIDEOS_START",
    FETCH_POPULAR_VIDEOS_SUCCESS: "FETCH_POPULAR_VIDEOS_SUCCESS",
    FETCH_POPULAR_VIDEOS_FAILED: "FETCH_POPULAR_VIDEOS_FAILED",

    FETCH_CATEGORY_VIDEOS_START: "FETCH_CATEGORY_VIDEOS_START",
    FETCH_CATEGORY_VIDEOS_SUCCESS: "FETCH_CATEGORY_VIDEOS_SUCCESS",
    FETCH_CATEGORY_VIDEOS_FAILED: "FETCH_CATEGORY_VIDEOS_FAILED"
}