export const RELATED_VIDEOS_ACTION_TYPES = {
    FETCH_RELATED_VIDEOS_START: "FETCH_RELATED_VIDEOS_START",
    FETCH_RELATED_VIDEOS_SUCCESS: "FETCH_RELATED_VIDEOS_SUCCESS",
    FETCH_RELATED_VIDEOS_FAILED: "FETCH_RELATED_VIDEOS_FAILED",
}