export const WATCH_VIDEO_ACTION_TYPES = {
    FETCH_VIDEO_BY_ID_START: "FETCH_VIDEO_BY_ID_START",
    FETCH_VIDEO_BY_ID_SUCCESS: "FETCH_VIDEO_BY_ID_SUCCESS",
    FETCH_VIDEO_BY_ID_FAILED: "FETCH_VIDEO_BY_ID_FAILED",
    
    FETCH_VIDEO_COMMENTS_START: "FETCH_VIDEO_COMMENTS_START",
    FETCH_VIDEO_COMMENTS_SUCCESS: "FETCH_VIDEO_COMMENTS_SUCCESS",
    FETCH_VIDEO_COMMENTS_FAILED: "FETCH_VIDEO_COMMENTS_FAILED",
}