export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    CHECK_USER_SESSION: "CHECK_USER_SESSION",
    GOOGLE_LOG_IN_START: "GOOGLE_LOG_IN_START",
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
    LOG_IN_FAILED: "LOG_IN_FAILED",
    LOG_OUT_START: "LOG_OUT_START",
    LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
    LOG_OUT_FAILED: "LOG_OUT_FAILED"
}