export const CHANNEL_VIDEOS_ACTION_TYPES = {
    FETCH_VIDEOS_BY_CHANNEL_START: "FETCH_VIDEOS_BY_CHANNEL_START",
    FETCH_VIDEOS_BY_CHANNEL_SUCCESS: "FETCH_VIDEOS_BY_CHANNEL_SUCCESS",
    FETCH_VIDEOS_BY_CHANNEL_FAILED: "FETCH_VIDEOS_BY_CHANNEL_FAILED",
}