export const COMMENTS_ACTION_TYPES = {
    FETCH_VIDEO_COMMENTS_START: "FETCH_VIDEO_COMMENTS_START",
    FETCH_VIDEO_COMMENTS_SUCCESS: "FETCH_VIDEO_COMMENTS_SUCCESS",
    FETCH_VIDEO_COMMENTS_FAILED: "FETCH_VIDEO_COMMENTS_FAILED",

    ADD_COMMENT_START:"ADD_COMMENT_START",
    ADD_COMMENT_SUCCESS:"ADD_COMMENT_SUCCESS",
    ADD_COMMENT_FAILED:"ADD_COMMENT_FAILED"
}