export const SUBSCRIPTIONS_ACTION_TYPES = {
    FETCH_SUBSCRIPTIONS_START: "FETCH_SUBSCRIPTIONS_START",
    FETCH_SUBSCRIPTIONS_SUCCESS: "FETCH_SUBSCRIPTIONS_SUCCESS",
    FETCH_SUBSCRIPTIONS_FAILED: "FETCH_SUBSCRIPTIONS_FAILED"
}